AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Haversack, a SAM template for bedrock-stream-gateway

Parameters:
  ApiKeySecretArn:
    Type: String
    AllowedPattern: ^arn:aws:secretsmanager:.*$
    Description: The secret ARN in Secrets Manager used to store the API Key (NB. The stored API key need to be in JSON format; i.e. {"api_key":"...."})
  DefaultModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: The default model ID, please make sure the model ID is supported in the current region
  DefaultEmbeddingModelId:
    Type: String
    Default: cohere.embed-multilingual-v3
  EnableCrossRegionInference:
    Type: String
    AllowedPattern: ^(true|false)$
    Default: "true"

Resources:
  Fun:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest
      DockerBuildArgs:
        # Basing on the official bedrock-access-gateway-ecs image; so make sure you login to their ECR (366590864501.dkr.ecr.$region.amazonaws.com) when you build us.
        region: !Ref AWS::Region
    Properties:
      Architectures: ['arm64']
      Timeout: 600
      Environment:
        Variables:
          DEBUG: "true"
          API_KEY_SECRET_ARN: !Ref ApiKeySecretArn
          DEFAULT_MODEL: !Ref DefaultModelId
          DEFAULT_EMBEDDING_MODEL: !Ref DefaultEmbeddingModelId
          ENABLE_CROSS_REGION_INFERENCE: !Ref EnableCrossRegionInference
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      MemorySize: 1024
      PackageType: Image
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Action:
                - bedrock:ListFoundationModels
                - bedrock:ListInferenceProfiles
              Effect: Allow
              Resource: "*"
            - Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Effect: Allow
              Resource:
                - arn:aws:bedrock:*::foundation-model/*
                - arn:aws:bedrock:*:*:inference-profile/*
            - Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Effect: Allow
              Resource:
                Ref: ApiKeySecretArn

Outputs:
  ApiUrl:
    Description: Endpoint URL
    Value: !GetAtt FunUrl.FunctionUrl
